# Copyright (c) 2026 Seqera Labs
# All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
apiVersion: v2
name: studios
description: Studios is a unified platform for interactive analysis
sources:
  - https://github.com/seqeralabs/helm-charts/tree/main/seqera/charts/studios
version: 1.2.0
appVersion: "0.9.0"
maintainers:
  - name: Seqera Labs
    email: devops@seqera.io
    url: https://seqera.io
dependencies:
  - name: common
    version: "2.x.x"
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
  - name: seqera-common
    version: "2.x.x"
    repository: "file://../../../seqera-common"
    tags:
      - seqera-common
