{{- $commonLabels := include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | fromYaml -}}
{{- $mergedlabels := include "common.tplvalues.merge" (dict "values" (list .Values.platform.configMapLabels $commonLabels) "context" .) -}}
{{- $labels := include "common.tplvalues.render" (dict "value" $mergedlabels "context" $) -}}
{{- $mergedAnnotations := include "common.tplvalues.merge" (dict "values" (list .Values.platform.configMapAnnotations .Values.commonAnnotations) "context" .) -}}
{{- $annotations := include "common.tplvalues.render" (dict "value" $mergedAnnotations "context" $) -}}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ printf "%s-backend" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- $labels | nindent 4 }}
  annotations: {{- $annotations | nindent 4 }}
data:
  MICRONAUT_ENVIRONMENTS: {{ include "platform.backend.micronautEnvs" . }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ printf "%s-cron" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- $labels | nindent 4 }}
  annotations: {{- $annotations | nindent 4 }}
data:
  MICRONAUT_ENVIRONMENTS: {{ include "platform.cron.micronautEnvs" . }}
  TOWER_CRON_SERVER_PORT: {{ .Values.cron.service.http.targetPort | int | quote }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ printf "%s-shared-backend-cron" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- $labels | nindent 4 }}
  annotations: {{- $annotations | nindent 4 }}
data:
  TOWER_SERVER_URL: {{ printf "https://%s" (tpl .Values.global.platformExternalDomain $) | quote }}
  TOWER_CONTENT_URL: {{ printf "https://%s" (tpl .Values.global.contentDomain $) | quote }}
  TOWER_CONTACT_EMAIL: {{ .Values.platform.contactEmail | quote }}

  TOWER_ENABLE_PLATFORMS: {{ uniq .Values.platform.executionBackends | join "," | quote }}

  TOWER_REDIS_URL: {{ include "platform.redis.uri" . | quote }}

  WAVE_SERVER_URL: {{ tpl .Values.platform.waveServerUrl $ | quote }}

  TOWER_DB_URL: {{ printf "jdbc:mysql://%s:%d/%s?&usePipelineAuth=false&useBatchMultiSend=false&permitMysqlScheme=true"
                          .Values.global.platformDatabase.host
                          (.Values.global.platformDatabase.port | int)
                          .Values.global.platformDatabase.database
                              | quote }}
  TOWER_DB_USER: {{ tpl .Values.global.platformDatabase.username . | quote }}
  TOWER_DB_DRIVER: {{ .Values.global.platformDatabase.driver | quote }}
  TOWER_DB_DIALECT: {{ .Values.global.platformDatabase.dialect | quote }}
  TOWER_DB_MAX_LIFETIME: {{ .Values.global.platformDatabase.maxLifetime | toString | quote }}
  TOWER_DB_MAX_POOL_SIZE: {{ .Values.global.platformDatabase.maxPoolSize | toString | quote }}
  TOWER_DB_MIN_POOL_SIZE: {{ .Values.global.platformDatabase.minPoolSize | toString | quote }}

{{- if .Values.platform.smtp.host }}
  TOWER_SMTP_HOST: {{ .Values.platform.smtp.host | quote }}
  TOWER_SMTP_PORT: {{ .Values.platform.smtp.port | quote }}
  TOWER_SMTP_USER: {{ .Values.platform.smtp.user | quote }}
{{- end }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ printf "%s-tower-yml" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- $labels | nindent 4 }}
  annotations: {{- $annotations | nindent 4 }}
data:
  tower.yml: |-
    {{- include "seqera.tplvalues.render" (dict "value" .Values.platform.YAMLConfigFileContent "context" $) | nindent 4 }}
