---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-backend" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
    app: backend
{{- with .Values.commonAnnotations }}
  annotations: {{- include "seqera.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}
{{- end }}

spec:
{{- $podLabels := include "common.tplvalues.merge" (dict "values" (list .Values.backend.podLabels .Values.commonLabels) "context" .) }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" (dict "customLabels" $podLabels "context" $) | nindent 6 }}
      app: backend

  # This prevents an empty dict {} to be rendered when extraOptionsSpec only contains keys that are
  # omitted (selector).
{{- $extraOptionsSpec := omit .Values.backend.extraOptionsSpec "selector" }}
{{- if $extraOptionsSpec }}
  {{- include "seqera.tplvalues.render" (dict "value" $extraOptionsSpec "context" $) | nindent 2 }}
{{- end }}

  template:
    metadata:
      labels: {{- include "common.labels.standard" (dict "customLabels" $podLabels "context" $) | nindent 8 }}
        app: backend
      annotations:
{{- if or .Values.backend.podAnnotations .Values.commonAnnotations }}
  {{- $podAnnotations := include "common.tplvalues.merge" (dict "values" (list .Values.backend.podAnnotations .Values.commonAnnotations) "context" $) }}
        {{- include "common.tplvalues.render" (dict "value" $podAnnotations "context" $) | nindent 8 }}
{{- end }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}

    spec:
      serviceAccountName: {{ include "platform.serviceAccountName" . }}
{{- if .Values.backend.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.backend.podSecurityContext "enabled" | toYaml | nindent 8 }}
{{- end }}
{{- $extraOptionsTemplateSpec := omit .Values.backend.extraOptionsTemplateSpec "serviceAccountName" "serviceAccount" "securityContext" "initContainers" "containers" "volumes" "imagePullSecrets" }}
{{- if $extraOptionsTemplateSpec }}
      {{- include "seqera.tplvalues.render" (dict "value" $extraOptionsTemplateSpec "context" $) | nindent 6 }}
{{- end }}

      initContainers:
{{- if .Values.initContainerDependencies.enabled }}
        {{- include "platform.initContainerWaitForDB" . | nindent 8 }}
        {{- include "platform.initContainerWaitForRedis" . | nindent 8 }}
        {{- include "platform.initContainerWaitForCron" . | nindent 8 }}
{{- end }}
{{- with .Values.backend.initContainers }}
        {{- include "seqera.tplvalues.render" (dict "value" . "context" $) | nindent 8 }}
{{- end }}

      containers:
        - name: backend
          image: {{ include "common.images.image" (dict "imageRoot" .Values.backend.image "global" .Values.global "chart" .Chart) }}
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
{{- with .Values.backend.command }}
          command: {{ toYaml . | nindent 12 }}
{{- end }}
{{- with .Values.backend.args }}
          args: {{ toYaml . | nindent 12 }}
{{- end }}

          envFrom:
            - configMapRef:
                name: {{ printf "%s-backend" (include "common.names.fullname" .) }}
            - configMapRef:
                name: {{ printf "%s-shared-backend-cron" (include "common.names.fullname" .) }}
{{/*
- secretRef:
{{/* TODO: Common secrets should be probably split into a separate resource.
name: {{ printf "%s-backend" (include "common.names.fullname" .) }}
*/}}
{{- range .Values.backend.extraEnvVarsCMs }}
            - configMapRef:
                name: {{ include "seqera.tplvalues.render" (dict "value" . "context" $) }}
{{- end }}
{{- range .Values.backend.extraEnvVarsSecrets }}
            - secretRef:
                name: {{ include "seqera.tplvalues.render" (dict "value" . "context" $) }}
{{- end }}

          env:
{{- if (include "platform.database.secretName" .) }}
            - name: TOWER_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "platform.database.secretName" . }}
                  key: {{ include "platform.database.secretKey" . }}
{{- end }}
{{- if (include "platform.license.secretName" .) }}
            - name: TOWER_LICENSE
              valueFrom:
                secretKeyRef:
                  name: {{ include "platform.license.secretName" . }}
                  key: {{ include "platform.license.secretKey" . }}
{{- end }}
{{- if (include "platform.jwt.secretName" .) }}
            - name: TOWER_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "platform.jwt.secretName" . }}
                  key: {{ include "platform.jwt.secretKey" . }}
{{- end }}
{{- if (include "platform.crypto.secretName" .) }}
            - name: TOWER_CRYPTO_SECRETKEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "platform.crypto.secretName" . }}
                  key: {{ include "platform.crypto.secretKey" . }}
{{- end }}
{{- if (include "platform.redis.secretName" .) }}
            - name: TOWER_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "platform.redis.secretName" . }}
                  key: {{ include "platform.redis.secretKey" . }}
{{- end }}
{{- if (include "platform.smtp.secretName" .) }}
            - name: TOWER_SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "platform.smtp.secretName" . }}
                  key: {{ include "platform.smtp.secretKey" . }}
{{- end }}

            - name: NXF_HOME
              value: "/var/cache/tower/"
            - name: NXF_PLUGINS_DIR
              value: "/var/cache/tower/plugins/"
{{- with .Values.backend.extraEnvVars }}
            {{- include "seqera.tplvalues.render" (dict "value" . "context" $) | nindent 12 }}
{{- end }}

{{- with .Values.backend.resources }}
          resources: {{- toYaml . | nindent 12 }}
{{- end }}

          volumeMounts:
{{- with .Values.backend.extraVolumeMounts }}
            {{- include "seqera.tplvalues.render" (dict "value" . "context" $) | nindent 12 }}
{{- end }}
            - name: config-volume
              mountPath: /tower.yml
              subPath: tower.yml
            - name: plugin-volume
              mountPath: /var/cache/tower/
            # The following mountpoints are workarounds due to bugs in Nextflow not obeying the NXF_PLUGINS_DIR/NXF_HOME vars.
            - name: plugin-volume
              mountPath: /.nextflow/
            - name: plugin-volume
              mountPath: /?/.nextflow/

{{- if .Values.backend.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.backend.containerSecurityContext "enabled" | toYaml | nindent 12 }}
{{- end }}

{{- if .Values.backend.livenessProbe.enabled }}
          livenessProbe: {{- include "seqera.tplvalues.render" (dict "value" (omit .Values.backend.livenessProbe "enabled") "context" $) | nindent 12 }}
{{- end }}
{{- if .Values.backend.readinessProbe.enabled }}
          readinessProbe: {{- include "seqera.tplvalues.render" (dict "value" (omit .Values.backend.readinessProbe "enabled") "context" $) | nindent 12 }}
{{- end }}
{{- if .Values.backend.startupProbe.enabled }}
          startupProbe: {{- include "seqera.tplvalues.render" (dict "value" (omit .Values.backend.startupProbe "enabled") "context" $) | nindent 12 }}
{{- end }}

      volumes:
{{- with .Values.backend.extraVolumes }}
        {{- include "seqera.tplvalues.render" (dict "value" . "context" $) | nindent 8 }}
{{- end }}
        - name: config-volume
          configMap:
            name: {{ printf "%s-tower-yml" (include "common.names.fullname" .) }}
        - name: plugin-volume
          emptyDir:
            sizeLimit: "1Gi"

      {{ include "common.images.renderPullSecrets" ( dict "images" (list .Values.backend.image) "context" $) | nindent 6 }}
