{{/*
 Copyright (c) 2025 Seqera Labs
 All rights reserved.

 SPDX-License-Identifier: Apache-2.0

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/}}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-cron" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
    app.kubernetes.io/component: cron
{{- with .Values.commonAnnotations }}
  annotations: {{- include "seqera.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}
{{- end }}

spec:
{{- $podLabels := include "common.tplvalues.merge" (dict "values" (list .Values.cron.podLabels .Values.commonLabels) "context" .) }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" (dict "customLabels" $podLabels "context" $) | nindent 6 }}
      app.kubernetes.io/component: cron

  # The cron deployment MUST NOT be replicated, not even during a rolling deployment.
  replicas: 1
  strategy:
    type: Recreate
  # This prevents an empty dict {} to be rendered when extraOptionsSpec only contains keys that are
  # omitted (replicas, strategy, selector).
{{- $extraOptionsSpec := omit .Values.cron.extraOptionsSpec "replicas" "strategy" "selector" }}
{{- if $extraOptionsSpec }}
  {{- include "seqera.tplvalues.render" (dict "value" $extraOptionsSpec "context" $) | nindent 2 }}
{{- end }}

  template:
    metadata:
      labels: {{- include "common.labels.standard" (dict "customLabels" $podLabels "context" $) | nindent 8 }}
        app.kubernetes.io/component: cron
      annotations:
{{- if or .Values.cron.podAnnotations .Values.commonAnnotations }}
  {{- $podAnnotations := include "common.tplvalues.merge" (dict "values" (list .Values.cron.podAnnotations .Values.commonAnnotations) "context" $) }}
        {{- include "common.tplvalues.render" (dict "value" $podAnnotations "context" $) | nindent 8 }}
{{- end }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}

    spec:
      serviceAccountName: {{ include "platform.serviceAccountName" . }}
{{- if .Values.cron.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.cron.podSecurityContext "enabled" | toYaml | nindent 8 }}
{{- end }}
{{- $extraOptionsTemplateSpec := omit .Values.cron.extraOptionsTemplateSpec "serviceAccountName" "serviceAccount" "securityContext" "initContainers" "containers" "volumes" "imagePullSecrets" }}
{{- if $extraOptionsTemplateSpec }}
      {{- include "seqera.tplvalues.render" (dict "value" $extraOptionsTemplateSpec "context" $) | nindent 6 }}
{{- end }}

      initContainers:
{{- if .Values.initContainerDependencies.enabled }}
        {{- include "platform.initContainerWaitForDB" . | nindent 8 }}
        {{- include "platform.initContainerWaitForRedis" . | nindent 8 }}
{{- end }}
        - name: migrate-db
          image: {{ include "common.images.image" (dict "imageRoot" .Values.cron.dbMigrationInitContainer.image "global" .Values.global "chart" .Chart) }}
          imagePullPolicy: {{ .Values.cron.dbMigrationInitContainer.image.pullPolicy }}
          command: {{- include "seqera.tplvalues.render" (dict "value" .Values.cron.dbMigrationInitContainer.command "context" $) | nindent 12 }}
          args: {{- include "seqera.tplvalues.render" (dict "value" .Values.cron.dbMigrationInitContainer.args "context" $) | nindent 12 }}
          env:
{{- with .Values.cron.dbMigrationInitContainer.extraEnvVars }}
            {{- include "seqera.tplvalues.render" (dict "value" . "context" $) | nindent 12 }}
{{- end }}
          envFrom:
            - configMapRef:
                name: {{ printf "%s-cron" (include "common.names.fullname" .) }}
            - configMapRef:
                name: {{ printf "%s-shared-backend-cron" (include "common.names.fullname" .) }}
            - secretRef:
                name: {{ printf "%s-backend" (include "common.names.fullname" .) }}
{{- range .Values.cron.dbMigrationInitContainer.extraEnvVarsCMs }}
            - configMapRef:
                name: {{ include "seqera.tplvalues.render" (dict "value" . "context" $) }}
{{- end }}
{{- range .Values.cron.dbMigrationInitContainer.extraEnvVarsSecrets }}
            - secretRef:
                name: {{ include "seqera.tplvalues.render" (dict "value" . "context" $) }}
{{- end }}

{{- if .Values.cron.dbMigrationInitContainer.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.cron.dbMigrationInitContainer.containerSecurityContext "enabled" | toYaml | nindent 12 }}
{{- end }}

{{- with .Values.cron.dbMigrationInitContainer.resources }}
          resources: {{- toYaml . | nindent 12 }}
{{- end }}
          volumeMounts:
{{- with .Values.cron.dbMigrationInitContainer.extraVolumeMounts }}
            {{- include "seqera.tplvalues.render" (dict "value" . "context" $) | nindent 12 }}
{{- end }}
            - name: config-volume
              mountPath: /tower.yml
              subPath: tower.yml
{{- with .Values.cron.initContainers }}
        {{- include "seqera.tplvalues.render" (dict "value" . "context" $) | nindent 8 }}
{{- end }}

      containers:
        - name: cron
          image: {{ include "common.images.image" (dict "imageRoot" .Values.cron.image "global" .Values.global "chart" .Chart) }}
          imagePullPolicy: {{ .Values.cron.image.pullPolicy }}
{{- with .Values.cron.command }}
          command: {{- toYaml . | nindent 12 }}
{{- end }}
{{- with .Values.cron.args }}
          args: {{- toYaml . | nindent 12 }}
{{- end }}

          envFrom:
            - configMapRef:
                name: {{ printf "%s-cron" (include "common.names.fullname" .) }}
            - configMapRef:
                name: {{ printf "%s-shared-backend-cron" (include "common.names.fullname" .) }}
{{- range .Values.cron.extraEnvVarsCMs }}
            - configMapRef:
                name: {{ include "seqera.tplvalues.render" (dict "value" . "context" $) }}
{{- end }}
{{- range .Values.cron.extraEnvVarsSecrets }}
            - secretRef:
                name: {{ include "seqera.tplvalues.render" (dict "value" . "context" $) }}
{{- end }}

          env:
            - name: TOWER_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "platform.database.secretName" . }}
                  key: {{ include "platform.database.secretKey" . }}
            - name: TOWER_LICENSE
              valueFrom:
                secretKeyRef:
                  name: {{ include "platform.license.secretName" . }}
                  key: {{ include "platform.license.secretKey" . }}
            - name: TOWER_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "platform.jwt.secretName" . }}
                  key: {{ include "platform.jwt.secretKey" . }}
            - name: TOWER_CRYPTO_SECRETKEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "platform.crypto.secretName" . }}
                  key: {{ include "platform.crypto.secretKey" . }}
{{- if or .Values.redis.password .Values.global.redis.password .Values.redis.existingSecretName .Values.global.redis.existingSecretName }}
            - name: TOWER_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "platform.redis.secretName" . }}
                  key: {{ include "platform.redis.secretKey" . }}
{{- end }}
{{- if .Values.platform.smtp.host }}
            - name: TOWER_SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "platform.smtp.secretName" . }}
                  key: {{ include "platform.smtp.secretKey" . }}
{{- end }}
            - name: NXF_HOME
              value: "/var/cache/tower/"
            - name: NXF_PLUGINS_DIR
              value: "/var/cache/tower/plugins/"
{{- with .Values.cron.extraEnvVars }}
            {{- include "seqera.tplvalues.render" (dict "value" . "context" $) | nindent 12 }}
{{- end }}

{{- with .Values.cron.resources }}
          resources: {{- toYaml . | nindent 12 }}
{{- end }}

          volumeMounts:
{{- with .Values.cron.extraVolumeMounts }}
            {{- include "seqera.tplvalues.render" (dict "value" . "context" $) | nindent 12 }}
{{- end }}
            - name: config-volume
              mountPath: /tower.yml
              subPath: tower.yml
            - name: plugin-volume
              mountPath: /var/cache/tower/
            # The following mountpoints are workarounds due to bugs in Nextflow not obeying the NXF_PLUGINS_DIR/NXF_HOME vars.
            - name: plugin-volume
              mountPath: /.nextflow/
            - name: plugin-volume
              mountPath: /?/.nextflow/

{{- if .Values.cron.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.cron.containerSecurityContext "enabled" | toYaml | nindent 12 }}
{{- end }}

{{- if .Values.cron.livenessProbe.enabled }}
          livenessProbe: {{- include "seqera.tplvalues.render" (dict "value" (omit .Values.cron.livenessProbe "enabled") "context" $) | nindent 12 }}
{{- end }}
{{- if .Values.cron.readinessProbe.enabled }}
          readinessProbe: {{- include "seqera.tplvalues.render" (dict "value" (omit .Values.cron.readinessProbe "enabled") "context" $) | nindent 12 }}
{{- end }}
{{- if .Values.cron.startupProbe.enabled }}
          startupProbe: {{- include "seqera.tplvalues.render" (dict "value" (omit .Values.cron.startupProbe "enabled") "context" $) | nindent 12 }}
{{- end }}

      volumes:
{{- with .Values.cron.extraVolumes }}
        {{- include "seqera.tplvalues.render" (dict "value" . "context" $) | nindent 8 }}
{{- end }}
        - name: config-volume
          configMap:
            name: {{ printf "%s-tower-yml" (include "common.names.fullname" .) }}
        - name: plugin-volume
          emptyDir:
            sizeLimit: "1Gi"

      {{ include "common.images.renderPullSecrets" ( dict "images" (list .Values.cron.image .Values.cron.dbMigrationInitContainer.image) "context" $) | nindent 6 }}
