{{ if .Values.ingress.enabled }}
  {{- $commonLabels := include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | fromYaml -}}
  {{- $mergedlabels := include "common.tplvalues.merge" (dict "values" (list .Values.ingress.extraLabels $commonLabels) "context" .) -}}
  {{- $labels := include "common.tplvalues.render" (dict "value" $mergedlabels "context" $) -}}
  {{- $mergedAnnotations := include "common.tplvalues.merge" (dict "values" (list .Values.ingress.annotations .Values.commonAnnotations) "context" .) -}}
  {{- $annotations := include "common.tplvalues.render" (dict "value" $mergedAnnotations "context" $) -}}

apiVersion: {{ include "common.capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- $labels | nindent 4 }}
  annotations: {{- $annotations | nindent 4 }}
spec:
  {{- with .Values.ingress.defaultBackend }}
  defaultBackend: {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}
  {{- end }}

  {{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName | quote }}
  {{- end }}

  {{- with .Values.ingress.tls }}
  tls: {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}
  {{- end }}

  rules:
    {{/* Hostname where to expose the main service. */}}
    - host: {{ tpl .Values.global.platformExternalDomain $ | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.path | quote }}
            pathType: {{ .Values.ingress.defaultPathType }}
            backend:
              service:
                name: {{ printf "%s-frontend" (include "common.names.fullname" .) | quote }}
                port:
                  number: {{ .Values.frontend.service.http.port }}

  {{- if (tpl .Values.global.contentDomain $) }}
    {{/* Hostname where Tower reports are exposed to the user. */}}
    - host: {{ tpl .Values.global.contentDomain $ | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.contentPath | quote }}
            pathType: {{ .Values.ingress.defaultPathType }}
            backend:
              service:
                name: {{ printf "%s-frontend" (include "common.names.fullname" .) | quote }}
                port:
                  number: {{ .Values.frontend.service.http.port }}
  {{- end }}

  {{- range .Values.ingress.extraHosts }}
    - host: {{ tpl .host $ | quote }}
      http:
        paths:
    {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType | default $.Values.ingress.defaultPathType }}
            backend:
              service:
                name: {{ tpl .serviceName $ | quote }}
                port:
                  number: {{ tpl .portNumber $ }}
    {{- end }}
  {{- end }}
{{- end }}
