---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    app.kubernetes.io/component: pipeline-optimization
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/component: pipeline-optimization
  ports:
    - name: {{ tpl .Values.service.http.name . }}
      port: {{ tpl (toString .Values.service.http.port) . | int }}
{{- $targetPort := tpl (toString .Values.service.http.targetPort) . }}
{{- if regexMatch "^[0-9]+$" $targetPort }}
      targetPort: {{ $targetPort | int }}
{{- else }}
      targetPort: {{ $targetPort }}
{{- end }}
{{- if and .Values.service.http.nodePort (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) }}
      nodePort: {{ .Values.service.http.nodePort }}
{{- end }}
{{- range .Values.service.extraServices }}
    - name: {{ tpl .name $ }}
      port: {{ tpl (toString .port) $ | int }}
  {{- $extraTargetPort := tpl (toString .targetPort) $ }}
  {{- if regexMatch "^[0-9]+$" $extraTargetPort }}
      targetPort: {{ $extraTargetPort | int }}
  {{- else }}
      targetPort: {{ $extraTargetPort }}
  {{- end }}
  {{- if and .nodePort (or (eq $.Values.service.type "NodePort") (eq $.Values.service.type "LoadBalancer")) }}
      nodePort: {{ .nodePort }}
  {{- end }}
{{- end }}
{{- with .Values.service.extraOptions }}
  {{- tpl (toYaml .) $ | nindent 2 }}
{{- end }}
